services:
  light-process:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./workflows:/workflows
    restart: unless-stopped
