name: Deploy

# Temporarily deploying from dev to test alphas on lp.enixcode.fr.
# Switch back to main for stable deploys later.
on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: []
    steps:
      - uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_DEPLOY_KEY }}
          script: light-process
